import XCTest
@testable import DoughKit

/// Cross-platform parity.
///
/// `fixtures/conformance.json` is generated by the Kotlin core (`gradle writeFixtures`), which
/// is compiled and tested on every push. These tests replay those golden values through the
/// Swift implementation, so iOS and Android cannot drift apart without something going red.
final class ConformanceTests: XCTestCase {
	private struct Fixtures: Decodable {
		struct RatePoint: Decodable {
			let temperatureC: Double
			let value: Double
		}

		struct EquivalentPoint: Decodable {
			let hours: Double
			let temperatureC: Double
			let value: Double
		}

		struct YeastPoint: Decodable {
			let equivalentHours: Double
			let saltPercent: Double
			let sugarPercent: Double
			let prefermentedFlourFraction: Double
			let wholeGrainFraction: Double
			let value: Double
		}

		struct LevainPoint: Decodable {
			let equivalentHours: Double
			let saltPercent: Double
			let wholeGrainFraction: Double
			let value: Double
		}

		struct SensingPoint: Decodable {
			let offsetMillis: Int64
			let doughC: Double?
			let heightMm: Double?
		}

		struct SensingCase: Decodable {
			let id: String
			let points: [SensingPoint]
			let measuredEquivalentHours: Double
			let effectiveConstantTemperatureC: Double?
			let longestGapMinutes: Double
			let elapsedHours: Double
			let expansionPercent: Double?
			let riseRatePercentPerHour: Double?
		}

		struct BlendPoint: Decodable {
			let styleId: String
			let proteinPercent: Double
			let wholeGrainFraction: Double
			let absorptionGuidePercent: Double
			let summary: String
		}

		struct PlanPoint: Decodable {
			let id: String
			let fermentationLoadHours: Double
			let totalHours: Double
			let hoursToReady: Double
			let stageCount: Int
		}

		struct IngredientPoint: Decodable {
			let id: String
			let grams: Double
			let bakersPercent: Double
		}

		struct FormulaPoint: Decodable {
			let styleId: String
			let totalDoughGrams: Double
			let totalFlourGrams: Double
			let totalWaterGrams: Double
			let prefermentFlourGrams: Double
			let prefermentTotalGrams: Double
			let prefermentBuild: [IngredientPoint]
			let finalMix: [IngredientPoint]
		}

		struct WaterPoint: Decodable {
			let desiredDoughTempC: Double
			let flourTempC: Double
			let roomTempC: Double
			let prefermentTempC: Double?
			let mixer: String
			let totalWaterGrams: Double
			let tapWaterTempC: Double
			let waterTemperatureC: Double
			let iceGrams: Double
			let waterGrams: Double
			let hasWarning: Bool
		}

		struct ProductionPoint: Decodable {
			let styleId: String
			let mixerCapacityKg: Double
			let mixCount: Int
			let ballsPerMix: [Int]
			let doughPerMixGrams: [Double]
		}

		let version: Int
		let rateMultipliers: [RatePoint]
		let equivalentHours: [EquivalentPoint]
		let instantYeast: [YeastPoint]
		let levain: [LevainPoint]
		let plans: [PlanPoint]
		let formulas: [FormulaPoint]
		let waterTemperatures: [WaterPoint]
		let production: [ProductionPoint]
		let blends: [BlendPoint]
		let sensing: [SensingCase]
	}

	/// Transcendental functions can differ in the last bit or two between platforms.
	private let tolerance = 1e-9

	private lazy var fixtures: Fixtures = {
		guard let url = Bundle.module.url(forResource: "conformance", withExtension: "json") else {
			fatalError("conformance.json is missing from the test bundle")
		}
		// swiftlint:disable:next force_try
		return try! JSONDecoder().decode(Fixtures.self, from: Data(contentsOf: url))
	}()

	private func assertClose(
		_ actual: Double,
		_ expected: Double,
		_ label: String,
		file: StaticString = #filePath,
		line: UInt = #line
	) {
		let allowed = max(tolerance, abs(expected) * tolerance)
		XCTAssertEqual(actual, expected, accuracy: allowed, label, file: file, line: line)
	}

	func testFixturesAreTheExpectedVersion() {
		XCTAssertEqual(fixtures.version, 1, "the fixture format changed — update these tests")
	}

	func testTemperatureRatesMatch() {
		for point in fixtures.rateMultipliers {
			assertClose(
				Fermentation.rateMultiplier(atC: point.temperatureC),
				point.value,
				"rate at \(point.temperatureC) °C"
			)
		}
	}

	func testEquivalentHoursMatch() {
		for point in fixtures.equivalentHours {
			assertClose(
				Fermentation.equivalentHours(hours: point.hours, atC: point.temperatureC),
				point.value,
				"\(point.hours)h at \(point.temperatureC) °C"
			)
		}
	}

	func testYeastDosesMatch() {
		for point in fixtures.instantYeast {
			assertClose(
				Leavening.instantYeastPercent(
					equivalentHours: point.equivalentHours,
					saltPercent: point.saltPercent,
					sugarPercent: point.sugarPercent,
					prefermentedFlourFraction: point.prefermentedFlourFraction,
					wholeGrainFraction: point.wholeGrainFraction
				),
				point.value,
				"yeast at \(point.equivalentHours) EH"
			)
		}
	}

	func testLevainDosesMatch() {
		for point in fixtures.levain {
			assertClose(
				Leavening.levainPercent(
					equivalentHours: point.equivalentHours,
					saltPercent: point.saltPercent,
					wholeGrainFraction: point.wholeGrainFraction
				),
				point.value,
				"levain at \(point.equivalentHours) EH"
			)
		}
	}

	func testPlanLibraryMatches() {
		XCTAssertEqual(
			FermentationPlan.library.map(\.id),
			fixtures.plans.map(\.id),
			"the two plan libraries have diverged"
		)
		for point in fixtures.plans {
			guard let plan = FermentationPlan.plan(id: point.id) else {
				return XCTFail("missing plan \(point.id)")
			}
			XCTAssertEqual(plan.stages.count, point.stageCount, "stage count for \(point.id)")
			assertClose(plan.fermentationLoadHours, point.fermentationLoadHours, "load for \(point.id)")
			assertClose(plan.totalHours, point.totalHours, "total hours for \(point.id)")
			assertClose(plan.hoursToReady, point.hoursToReady, "hours to ready for \(point.id)")
		}
	}

	func testStyleFormulasMatch() {
		XCTAssertEqual(
			DoughStyle.library.map(\.id),
			fixtures.formulas.map(\.styleId),
			"the two style libraries have diverged"
		)
		for point in fixtures.formulas {
			guard let style = DoughStyle.style(id: point.styleId) else {
				return XCTFail("missing style \(point.styleId)")
			}
			let result = style.formula.result()
			assertClose(result.totalDoughGrams, point.totalDoughGrams, "dough for \(point.styleId)")
			assertClose(result.totalFlourGrams, point.totalFlourGrams, "flour for \(point.styleId)")
			assertClose(result.totalWaterGrams, point.totalWaterGrams, "water for \(point.styleId)")
			assertClose(
				result.prefermentFlourGrams,
				point.prefermentFlourGrams,
				"preferment flour for \(point.styleId)"
			)
			assertClose(
				result.prefermentTotalGrams,
				point.prefermentTotalGrams,
				"preferment total for \(point.styleId)"
			)

			XCTAssertEqual(
				result.prefermentBuild.map(\.id),
				point.prefermentBuild.map(\.id),
				"preferment build rows for \(point.styleId)"
			)
			for (row, expected) in zip(result.prefermentBuild, point.prefermentBuild) {
				assertClose(row.grams, expected.grams, "\(point.styleId) build \(row.id)")
			}

			XCTAssertEqual(
				result.finalMix.map(\.id),
				point.finalMix.map(\.id),
				"final mix rows for \(point.styleId)"
			)
			for (row, expected) in zip(result.finalMix, point.finalMix) {
				assertClose(row.grams, expected.grams, "\(point.styleId) mix \(row.id)")
				assertClose(row.bakersPercent, expected.bakersPercent, "\(point.styleId) mix % \(row.id)")
			}
		}
	}

	func testWaterTemperaturesMatch() {
		for point in fixtures.waterTemperatures {
			guard let mixer = Self.mixer(named: point.mixer) else {
				return XCTFail("unknown mixer \(point.mixer)")
			}
			let solved = DoughTemperature.solve(
				desiredDoughTempC: point.desiredDoughTempC,
				flourTempC: point.flourTempC,
				roomTempC: point.roomTempC,
				prefermentTempC: point.prefermentTempC,
				mixer: mixer,
				totalWaterGrams: point.totalWaterGrams,
				tapWaterTempC: point.tapWaterTempC
			)
			assertClose(solved.waterTemperatureC, point.waterTemperatureC, "water temp")
			assertClose(solved.iceGrams, point.iceGrams, "ice")
			assertClose(solved.waterGrams, point.waterGrams, "water")
			XCTAssertEqual(solved.warning != nil, point.hasWarning, "warning flag")
		}
	}

	func testProductionSplitsMatch() {
		for point in fixtures.production {
			guard let style = DoughStyle.style(id: point.styleId) else {
				return XCTFail("missing style \(point.styleId)")
			}
			let plan = style.formula.result().productionPlan(mixerCapacityKg: point.mixerCapacityKg)
			XCTAssertEqual(plan.mixCount, point.mixCount, "mix count for \(point.styleId)")
			XCTAssertEqual(plan.mixes.map(\.ballCount), point.ballsPerMix, "balls for \(point.styleId)")
			for (mix, expected) in zip(plan.mixes, point.doughPerMixGrams) {
				assertClose(mix.doughGrams, expected, "\(point.styleId) mix \(mix.id) dough")
			}
		}
	}

	func testFlourBlendsMatch() {
		XCTAssertEqual(
			DoughStyle.library.map(\.id),
			fixtures.blends.map(\.styleId),
			"the two style libraries have diverged"
		)
		for point in fixtures.blends {
			guard let style = DoughStyle.style(id: point.styleId) else {
				return XCTFail("missing style \(point.styleId)")
			}
			let blend = style.formula.blend
			assertClose(blend.proteinPercent, point.proteinPercent, "protein for \(point.styleId)")
			assertClose(
				blend.wholeGrainFraction,
				point.wholeGrainFraction,
				"whole grain share for \(point.styleId)"
			)
			assertClose(
				blend.absorptionGuidePercent,
				point.absorptionGuidePercent,
				"absorption guide for \(point.styleId)"
			)
			XCTAssertEqual(blend.summary, point.summary, "blend summary for \(point.styleId)")
		}
	}

	func testSensingMatches() {
		for point in fixtures.sensing {
			let series = SensorSeries(
				point.points.map { sample in
					SensorReading(
						date: Date(timeIntervalSince1970: Double(sample.offsetMillis) / 1000),
						doughTempC: sample.doughC,
						doughHeightMm: sample.heightMm
					)
				}
			)

			assertClose(series.elapsedHours, point.elapsedHours, "elapsed for \(point.id)")
			assertClose(
				series.measuredEquivalentHours(),
				point.measuredEquivalentHours,
				"measured equivalent hours for \(point.id)"
			)
			assertClose(
				series.longestTemperatureGapMinutes(),
				point.longestGapMinutes,
				"gap for \(point.id)"
			)

			if let expected = point.effectiveConstantTemperatureC {
				guard let actual = series.effectiveConstantTemperatureC() else {
					return XCTFail("no effective temperature for \(point.id)")
				}
				// Both sides bisect to convergence, so this is tighter than the model's own error.
				XCTAssertEqual(actual, expected, accuracy: 1e-6, "effective temperature for \(point.id)")
			} else {
				XCTAssertNil(series.effectiveConstantTemperatureC(), "\(point.id) should have none")
			}

			if let expected = point.expansionPercent {
				guard let actual = series.expansionPercent() else {
					return XCTFail("no expansion for \(point.id)")
				}
				assertClose(actual, expected, "expansion for \(point.id)")
			} else {
				XCTAssertNil(series.expansionPercent(), "\(point.id) should have no expansion")
			}

			if let expected = point.riseRatePercentPerHour {
				guard let actual = series.riseRatePercentPerHour() else {
					return XCTFail("no rise rate for \(point.id)")
				}
				assertClose(actual, expected, "rise rate for \(point.id)")
			} else {
				XCTAssertNil(series.riseRatePercentPerHour(), "\(point.id) should have no rise rate")
			}
		}
	}

	/// The Kotlin side serialises enum case names; map them back.
	private static func mixer(named name: String) -> MixerKind? {
		switch name {
		case "HAND": .hand
		case "FORK": .fork
		case "DOUBLE_ARM": .doubleArm
		case "DIVING_ARM": .divingArm
		case "SPIRAL": .spiral
		case "PLANETARY": .planetary
		default: nil
		}
	}
}
