package com.blahmonster.prooflab.core

/** A starting point: a formula plus the fermentation plan it's usually run on. */
data class DoughStyle(
	val id: String,
	val name: String,
	val family: PlanFamily,
	val blurb: String,
	val formula: DoughFormula,
	val planId: String,
) {
	val plan: FermentationPlan get() = PlanLibrary.plan(planId) ?: PlanLibrary.coldBallRetard
}

object StyleLibrary {
	val all = listOf(
		DoughStyle(
			id = "neapolitan",
			name = "Neapolitan",
			family = PlanFamily.PIZZA,
			blurb = "00 flour, no oil, no sugar. Soft, blistered, gone in four bites.",
			formula = DoughFormula(
				name = "Neapolitan",
				ballCount = 20,
				ballWeightGrams = 250.0,
				hydrationPercent = 62.0,
				saltPercent = 2.8,
				instantYeastPercent = 0.1,
				flours = listOf(FlourLibrary.at("00-pizzeria", 100.0)),
				flourNote = "Type 00, W 260–300",
			),
			planId = PlanLibrary.neapolitanDirect.id,
		),
		DoughStyle(
			id = "new-york",
			name = "New York",
			family = PlanFamily.PIZZA,
			blurb = "Oil and a touch of sugar for a foldable slice that browns evenly.",
			formula = DoughFormula(
				name = "New York",
				ballCount = 20,
				ballWeightGrams = 340.0,
				hydrationPercent = 62.0,
				saltPercent = 2.0,
				oilPercent = 2.0,
				sugarPercent = 1.5,
				instantYeastPercent = 0.21,
				flours = listOf(FlourLibrary.at("high-gluten", 100.0)),
				flourNote = "High-gluten bread flour, 13–14 % protein",
			),
			planId = PlanLibrary.coldBallRetard.id,
		),
		DoughStyle(
			id = "detroit",
			name = "Detroit",
			family = PlanFamily.PIZZA,
			blurb = "Wet, slack, pressed into steel. Cheese to the edges, crust to the corners.",
			formula = DoughFormula(
				name = "Detroit",
				ballCount = 6,
				ballWeightGrams = 400.0,
				hydrationPercent = 70.0,
				saltPercent = 2.0,
				oilPercent = 3.0,
				instantYeastPercent = 0.3,
				flours = listOf(FlourLibrary.at("bread", 100.0)),
				flourNote = "Bread flour",
			),
			planId = PlanLibrary.detroitPan.id,
		),
		DoughStyle(
			id = "sicilian",
			name = "Sicilian / grandma",
			family = PlanFamily.PIZZA,
			blurb = "Oily pan dough, tender crumb, crisp fried bottom.",
			formula = DoughFormula(
				name = "Sicilian",
				ballCount = 4,
				ballWeightGrams = 700.0,
				hydrationPercent = 72.0,
				saltPercent = 2.2,
				oilPercent = 4.0,
				instantYeastPercent = 0.35,
				flours = listOf(FlourLibrary.at("bread", 100.0)),
				flourNote = "Bread flour",
			),
			planId = PlanLibrary.coldBulkRetard.id,
		),
		DoughStyle(
			id = "roman-teglia",
			name = "Roman teglia",
			family = PlanFamily.PIZZA,
			blurb = "Very high hydration, cold bulk, airy honeycomb crumb.",
			formula = DoughFormula(
				name = "Roman teglia",
				ballCount = 4,
				ballWeightGrams = 750.0,
				hydrationPercent = 80.0,
				saltPercent = 2.2,
				oilPercent = 3.0,
				instantYeastPercent = 0.3,
				flours = listOf(FlourLibrary.at("00-strong", 80.0), FlourLibrary.at("semola", 20.0)),
				flourNote = "Strong 00 or a W 330+ blend",
			),
			planId = PlanLibrary.coldBulkRetard.id,
		),
		DoughStyle(
			id = "contemporary-biga",
			name = "Contemporary — biga",
			family = PlanFamily.PIZZA,
			blurb = "Stiff biga at 60 % of the flour. Cloud-like cornicione.",
			formula = DoughFormula(
				name = "Contemporary biga",
				ballCount = 16,
				ballWeightGrams = 280.0,
				hydrationPercent = 72.0,
				saltPercent = 2.6,
				instantYeastPercent = 0.08,
				prefermentKind = PrefermentKind.BIGA,
				prefermentedFlourPercent = 60.0,
				prefermentHydrationPercent = 50.0,
				prefermentYeastPercent = 0.12,
				flours = listOf(FlourLibrary.at("00-strong", 100.0)),
				flourNote = "Strong 00, W 320+",
			),
			planId = PlanLibrary.bigaPizza.id,
		),
		DoughStyle(
			id = "poolish-pizza",
			name = "Poolish pizza",
			family = PlanFamily.PIZZA,
			blurb = "Overnight poolish for extensibility and a sweeter crumb.",
			formula = DoughFormula(
				name = "Poolish pizza",
				ballCount = 16,
				ballWeightGrams = 270.0,
				hydrationPercent = 68.0,
				saltPercent = 2.5,
				instantYeastPercent = 0.1,
				prefermentKind = PrefermentKind.POOLISH,
				prefermentedFlourPercent = 30.0,
				prefermentHydrationPercent = 100.0,
				prefermentYeastPercent = 0.15,
				flours = listOf(FlourLibrary.at("00-pizzeria", 100.0)),
				flourNote = "00 or bread flour",
			),
			planId = PlanLibrary.poolishPizza.id,
		),
		DoughStyle(
			id = "sourdough-pizza",
			name = "Sourdough pizza",
			family = PlanFamily.PIZZA,
			blurb = "Levain-leavened, cold-retarded balls. Tang without sourness.",
			formula = DoughFormula(
				name = "Sourdough pizza",
				ballCount = 12,
				ballWeightGrams = 270.0,
				hydrationPercent = 66.0,
				saltPercent = 2.5,
				leaven = LeavenKind.SOURDOUGH,
				instantYeastPercent = 0.0,
				prefermentKind = PrefermentKind.LEVAIN,
				prefermentedFlourPercent = 10.0,
				prefermentHydrationPercent = 100.0,
				flours = listOf(FlourLibrary.at("bread", 90.0), FlourLibrary.at("whole-wheat", 10.0)),
				flourNote = "Bread flour with 10 % whole wheat",
			),
			planId = PlanLibrary.sourdoughPizzaCold.id,
		),
		DoughStyle(
			id = "sourdough-neapolitan",
			name = "Sourdough Neapolitan",
			family = PlanFamily.PIZZA,
			blurb = "Naples rhythm on a levain — no fridge, a touch of semola for bite.",
			formula = DoughFormula(
				name = "Sourdough Neapolitan",
				ballCount = 16,
				ballWeightGrams = 250.0,
				hydrationPercent = 63.0,
				saltPercent = 2.8,
				leaven = LeavenKind.SOURDOUGH,
				instantYeastPercent = 0.0,
				prefermentKind = PrefermentKind.LEVAIN,
				prefermentedFlourPercent = 8.0,
				prefermentHydrationPercent = 100.0,
				flours = listOf(FlourLibrary.at("00-pizzeria", 90.0), FlourLibrary.at("semola", 10.0)),
				flourNote = "Keep the levain young or it'll read sour in a 60-second bake",
			),
			planId = PlanLibrary.sourdoughRoomPizza.id,
		),
		DoughStyle(
			id = "sourdough-new-york",
			name = "Sourdough New York",
			family = PlanFamily.PIZZA,
			blurb = "Foldable slice with a levain tang. Oil for browning, whole wheat for depth.",
			formula = DoughFormula(
				name = "Sourdough New York",
				ballCount = 16,
				ballWeightGrams = 340.0,
				hydrationPercent = 65.0,
				saltPercent = 2.2,
				oilPercent = 2.0,
				leaven = LeavenKind.SOURDOUGH,
				instantYeastPercent = 0.0,
				prefermentKind = PrefermentKind.LEVAIN,
				prefermentedFlourPercent = 10.0,
				prefermentHydrationPercent = 100.0,
				flours = listOf(
					FlourLibrary.at("high-gluten", 85.0),
					FlourLibrary.at("whole-wheat", 15.0),
				),
				flourNote = "High-gluten carries the long cold retard",
			),
			planId = PlanLibrary.sourdoughPizzaCold.id,
		),
		DoughStyle(
			id = "sourdough-pan",
			name = "Sourdough pan",
			family = PlanFamily.PIZZA,
			blurb = "Detroit-style on a levain. Slack, oily, proofed to the rim of the pan.",
			formula = DoughFormula(
				name = "Sourdough pan",
				ballCount = 4,
				ballWeightGrams = 420.0,
				hydrationPercent = 75.0,
				saltPercent = 2.0,
				oilPercent = 3.0,
				leaven = LeavenKind.SOURDOUGH,
				instantYeastPercent = 0.0,
				prefermentKind = PrefermentKind.LEVAIN,
				prefermentedFlourPercent = 12.0,
				prefermentHydrationPercent = 100.0,
				flours = listOf(FlourLibrary.at("bread", 100.0)),
				flourNote = "Bread flour; a stronger flour fights the pan",
			),
			planId = PlanLibrary.sourdoughPanCold.id,
		),
		DoughStyle(
			id = "sourdough-teglia",
			name = "Sourdough teglia",
			family = PlanFamily.PIZZA,
			blurb = "Roman tray pizza on a levain. Very wet, very open, cut with a scissor.",
			formula = DoughFormula(
				name = "Sourdough teglia",
				ballCount = 3,
				ballWeightGrams = 800.0,
				hydrationPercent = 82.0,
				saltPercent = 2.2,
				oilPercent = 3.0,
				leaven = LeavenKind.SOURDOUGH,
				instantYeastPercent = 0.0,
				prefermentKind = PrefermentKind.LEVAIN,
				prefermentedFlourPercent = 10.0,
				prefermentHydrationPercent = 100.0,
				flours = listOf(
					FlourLibrary.at("00-strong", 70.0),
					FlourLibrary.at("semola", 20.0),
					FlourLibrary.at("whole-wheat", 10.0),
				),
				flourNote = "Needs a strong flour to hold 82 %",
			),
			planId = PlanLibrary.sourdoughPanCold.id,
		),
		DoughStyle(
			id = "semola-blend",
			name = "Semola blend pizza",
			family = PlanFamily.PIZZA,
			blurb = "00 cut with semola: more bite, more colour, a slightly shorter dough.",
			formula = DoughFormula(
				name = "Semola blend",
				ballCount = 16,
				ballWeightGrams = 270.0,
				hydrationPercent = 65.0,
				saltPercent = 2.6,
				instantYeastPercent = 0.15,
				flours = listOf(FlourLibrary.at("00-pizzeria", 70.0), FlourLibrary.at("semola", 30.0)),
				flourNote = "Semola drinks less — expect a firmer dough at the same number",
			),
			planId = PlanLibrary.coldBallRetard.id,
		),
		DoughStyle(
			id = "whole-grain-pizza",
			name = "Half whole-grain pizza",
			family = PlanFamily.PIZZA,
			blurb = "Fifty per cent whole grain. Nutty, fast-fermenting, needs less leaven than it looks.",
			formula = DoughFormula(
				name = "Half whole-grain",
				ballCount = 12,
				ballWeightGrams = 280.0,
				hydrationPercent = 72.0,
				saltPercent = 2.3,
				leaven = LeavenKind.SOURDOUGH,
				instantYeastPercent = 0.0,
				prefermentKind = PrefermentKind.LEVAIN,
				prefermentedFlourPercent = 9.0,
				prefermentHydrationPercent = 100.0,
				flours = listOf(
					FlourLibrary.at("bread", 50.0),
					FlourLibrary.at("whole-wheat", 40.0),
					FlourLibrary.at("kamut", 10.0),
				),
				flourNote = "Bran cuts the gluten — handle gently and don't over-bulk",
			),
			planId = PlanLibrary.sourdoughPizzaCold.id,
		),
		DoughStyle(
			id = "country-loaf",
			name = "Country sourdough",
			family = PlanFamily.BREAD,
			blurb = "Bread flour with a little whole grain, overnight cold proof.",
			formula = DoughFormula(
				name = "Country sourdough",
				ballCount = 2,
				ballWeightGrams = 900.0,
				hydrationPercent = 76.0,
				saltPercent = 2.0,
				leaven = LeavenKind.SOURDOUGH,
				instantYeastPercent = 0.0,
				prefermentKind = PrefermentKind.LEVAIN,
				prefermentedFlourPercent = 10.0,
				prefermentHydrationPercent = 100.0,
				flours = listOf(
					FlourLibrary.at("bread", 80.0),
					FlourLibrary.at("whole-wheat", 15.0),
					FlourLibrary.at("rye", 5.0),
				),
				flourNote = "A little rye keeps the levain lively",
			),
			planId = PlanLibrary.sourdoughCountryLoaf.id,
		),
		DoughStyle(
			id = "focaccia",
			name = "Focaccia",
			family = PlanFamily.BREAD,
			blurb = "Olive oil, sea salt, dimples all the way to the bottom of the pan.",
			formula = DoughFormula(
				name = "Focaccia",
				ballCount = 2,
				ballWeightGrams = 1000.0,
				hydrationPercent = 80.0,
				saltPercent = 2.2,
				oilPercent = 5.0,
				instantYeastPercent = 0.25,
				flours = listOf(FlourLibrary.at("bread", 100.0)),
				flourNote = "Bread flour",
			),
			planId = PlanLibrary.focacciaColdBulk.id,
		),
		DoughStyle(
			id = "baguette",
			name = "Baguette",
			family = PlanFamily.BREAD,
			blurb = "Poolish at 40 %, restrained bulk, thin crackling crust.",
			formula = DoughFormula(
				name = "Baguette",
				ballCount = 6,
				ballWeightGrams = 350.0,
				hydrationPercent = 72.0,
				saltPercent = 2.0,
				instantYeastPercent = 0.12,
				prefermentKind = PrefermentKind.POOLISH,
				prefermentedFlourPercent = 40.0,
				prefermentHydrationPercent = 100.0,
				prefermentYeastPercent = 0.12,
				flours = listOf(FlourLibrary.at("t65", 100.0)),
				flourNote = "T65 or unbleached AP",
			),
			planId = PlanLibrary.poolishBaguette.id,
		),
		DoughStyle(
			id = "enriched",
			name = "Enriched sandwich",
			family = PlanFamily.BREAD,
			blurb = "Sugar, butter, milk powder. Soft crumb, quick same-day schedule.",
			formula = DoughFormula(
				name = "Enriched sandwich",
				ballCount = 3,
				ballWeightGrams = 800.0,
				hydrationPercent = 64.0,
				saltPercent = 2.0,
				oilPercent = 8.0,
				sugarPercent = 10.0,
				instantYeastPercent = 0.6,
				flours = listOf(FlourLibrary.at("bread", 100.0)),
				flourNote = "Bread flour",
			),
			planId = PlanLibrary.sameDayStraight.id,
		),
	)

	fun style(id: String): DoughStyle? = all.firstOrNull { it.id == id }

	fun styles(family: PlanFamily): List<DoughStyle> = all.filter { it.family == family }

	/** Every style leavened with a levain — the sourdough shelf. */
	val sourdough: List<DoughStyle> get() = all.filter { it.formula.leaven == LeavenKind.SOURDOUGH }
}
